*&---------------------------------------------------------------------*
*& Report ZEA_CHECK_MT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEA_MMT090 MESSAGE-ID ZEA_MSG.

INCLUDE ZEA_MM090TOP.
*INCLUDE ZEA_MMT090TOP.
*INCLUDE ZEA_MMT090_2TOP.

INCLUDE ZEA_MM090SCR.
*INCLUDE ZEA_MMT090SCR.
*INCLUDE ZEA_MMT090_2SCR.

INCLUDE ZEA_MM090CLS.
*INCLUDE ZEA_MMT090CLS.
*INCLUDE ZEA_MMT090_2CLS.

INCLUDE ZEA_MM090PBO.
*INCLUDE ZEA_MMT090PBO.
*INCLUDE ZEA_MMT090_2PBO.

INCLUDE ZEA_MM090PAI.
*INCLUDE ZEA_MMT090PAI.
*INCLUDE ZEA_MMT090_2PAI.

INCLUDE ZEA_MM090F01.
*INCLUDE ZEA_MMT090F01.
*INCLUDE ZEA_MMT090_2F01.


INITIALIZATION.

AT SELECTION-SCREEN OUTPUT.

AT SELECTION-SCREEN.

START-OF-SELECTION.

PERFORM SELECT_DATA.
PERFORM MAKE_DISPLAY_DATA.
PERFORM DISPLAY_DATA.
