*&---------------------------------------------------------------------*
*& Include          YE00_EX007TOP
*&---------------------------------------------------------------------*

TABLES: ZEA_MMT090, ZEA_MMT100, ZEA_T001W, ZEA_MMT010, ZEA_MMT020.
*-- Database Table에서 조회 후 출력을 위한 Internal Tables
DATA: BEGIN OF GS_HEADER,
        GJAHR   LIKE ZEA_MMT090-GJAHR,   "회계연도
        WERKS   LIKE ZEA_MMT090-WERKS,   "플랜트ID
        PNAME1  LIKE ZEA_T001W-PNAME1,   " 플랜트명
        MATTYPE LIKE ZEA_MMT010-MATTYPE, " 자재유형
        MATNR   LIKE ZEA_MMT100-MATNR,   " 자재코드
        MAKTX   LIKE ZEA_MMT020-MAKTX,   " 자재코드 명

      END OF GS_HEADER,
      GT_HEADER LIKE TABLE OF GS_HEADER.

DATA: BEGIN OF GS_DISPLAY,
        GJAHR   LIKE ZEA_MMT090-GJAHR,   " 회계연도
        MBLNR   LIKE ZEA_MMT090-MBLNR,   " 자재문서번호
        BUDAT   LIKE ZEA_MMT090-BUDAT,   " 전기일자
        WERKS   LIKE ZEA_MMT090-WERKS,   " 플랜트ID
        PNAME1  LIKE ZEA_T001W-PNAME1,   " 플랜트명
        MATTYPE LIKE ZEA_MMT010-MATTYPE, " 자재유형
        CHARG   LIKE ZEA_MMT100-CHARG,
        MBGNO   LIKE ZEA_MMT100-MBGNO,   " 자재문서 품목번호
        MATNR   LIKE ZEA_MMT100-MATNR,   " 자재코드
        MAKTX   LIKE ZEA_MMT020-MAKTX,   " 자재코드 명
        PONUM   LIKE ZEA_MMT100-PONUM,
        AUFNR   LIKE ZEA_MMT100-AUFNR,
        SBELNR  LIKE ZEA_MMT100-SBELNR,
        BWART   LIKE ZEA_MMT100-BWART,   " 이동유형
        PLANTFR LIKE ZEA_MMT100-PLANTFR, " 시작정보(플랜트)
        PLANTTO LIKE ZEA_MMT100-PLANTTO, " 도착정보(플랜트)
        LGORTFR LIKE ZEA_MMT100-LGORTFR, " 저장위치(시작)
        LGORTTO LIKE ZEA_MMT100-LGORTTO, " 저장위치(도착)
        DMBTR   LIKE ZEA_MMT100-DMBTR,   " 통화금액(KRW)
        WAERS1  LIKE ZEA_MMT100-WAERS1,  " 통화코드
        MENGE   LIKE ZEA_MMT100-MENGE,   " 수량
        MEINS   LIKE ZEA_MMT100-MEINS,   " 단위
        GRUND   LIKE ZEA_MMT100-GRUND,   " 자재 이동사유
        VENCODE LIKE ZEA_MMT100-VENCODE, " [BP] 벤더코드
        CUSCODE LIKE ZEA_MMT100-CUSCODE, " [BP] 고객코드





      END OF GS_DISPLAY,

      GT_DISPLAY LIKE TABLE OF GS_DISPLAY.


*-- SCREEN 관련 변수
CONSTANTS: GC_CUSTOM_CONTAINER_NAME TYPE SCRFNAME VALUE 'CCON'.
DATA: OK_CODE TYPE SY-UCOMM.

DATA: GO_DOCKING_CONTAINER TYPE REF TO CL_GUI_DOCKING_CONTAINER,
      GO_CUSTOM_CONTAINER  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

      GO_SIMPLE_TREE       TYPE REF TO CL_GUI_SIMPLE_TREE,
      GO_ALV_GRID          TYPE REF TO CL_GUI_ALV_GRID.

*-- ALV 관련 변수
DATA: GS_LAYOUT   TYPE LVC_S_LAYO,
      GT_FIELDCAT TYPE LVC_T_FCAT,
      GS_FIELDCAT LIKE LINE OF GT_FIELDCAT,
      GT_SORT     TYPE LVC_T_SORT,
      GS_SORT     LIKE LINE OF GT_SORT,
      GS_VARIANT  TYPE DISVARIANT,
      GV_SAVE     TYPE C.

*-- TREE 관련 변수
DATA: GT_NODE TYPE TABLE OF MTREESNODE,
      GS_NODE LIKE LINE OF GT_NODE.

DATA: BEGIN OF GS_NODE_INFO,
        NODE_KEY LIKE MTREESNODE-NODE_KEY,
        GJAHR    LIKE ZEA_MMT090-GJAHR,
        WERKS    LIKE ZEA_MMT090-WERKS,
        MATTYPE  LIKE ZEA_MMT010-MATTYPE,
        MATNR    LIKE ZEA_MMT010-MATNR,
      END OF GS_NODE_INFO,

      GT_NODE_INFO LIKE TABLE OF GS_NODE_INFO.
