*&---------------------------------------------------------------------*
*& Include          YE07_STROTOP
*&---------------------------------------------------------------------*

TABLES: ZEA_MMT060, ZEA_PPT020, ZEA_AUFK, ZEA_AFRU, ZEA_T001W.

*CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.

DATA: BEGIN OF GS_DATA,
        WERKS TYPE ZEA_MMT060-WERKS,
        SCODE TYPE ZEA_MMT060-SCODE,
        STYPE TYPE ZEA_MMT060-STYPE,
        SNAME TYPE ZEA_MMT060-SNAME,
        STTEL TYPE ZEA_MMT060-STTEL,
        ADDRESS TYPE ZEA_MMT060-ADDRESS,
        TELNO TYPE ZEA_MMT060-TELNO,
        PNAME1 TYPE ZEA_T001W-PNAME1,
      END OF GS_DATA.

DATA GT_DATA LIKE TABLE OF GS_DATA.

  DATA: BEGIN OF GS_DISPLAY.
      INCLUDE STRUCTURE GS_DATA.
DATA: STATUS TYPE ICON-ID,

      END OF GS_DISPLAY.

DATA GT_DISPLAY LIKE TABLE OF GS_DISPLAY.

DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID.
*      GO_EVENT_HANDLER TYPE REF TO LCL_EVENT_HANDLER.

DATA: GS_VARIANT TYPE DISVARIANT,
      GV_SAVE TYPE C,

      GT_FIELDCAT TYPE LVC_T_FCAT,
      GS_FIELDCAT TYPE LVC_S_FCAT,

      GS_LAYOUT TYPE LVC_S_LAYO,

      GT_FILTER TYPE LVC_T_FILT,
      GS_FILTER TYPE LVC_S_FILT,

      GT_INDEX_ROWS TYPE LVC_T_ROW,
      GS_INDEX_ROWS TYPE LVC_S_ROW,

      OK_CODE TYPE SY-UCOMM,
      GV_LINES TYPE SY-TFILL,
      GV_ANSWER TYPE CHAR1,
      GV_CHANGED.


      DEFINE _MC_POPUP_CONFIRM.
  CALL FUNCTION 'POPUP_TO_CONFIRM'
    EXPORTING
      TITLEBAR              = &1
*      DISPLAY_CANCEL_BUTTON = ''
      TEXT_QUESTION         = &2
      TEXT_BUTTON_1         = 'YES'
      ICON_BUTTON_1         = '@2K@'
      TEXT_BUTTON_2         = 'NO'
      ICON_BUTTON_2         = '@2O@ '
    IMPORTING
      ANSWER                = &3
    EXCEPTIONS
      TEXT_NOT_FOUND        = 1
      OTHERS                = 2.
END-OF-DEFINITION.

CONSTANTS : GC_FACTORY TYPE STRING VALUE 'FACTORY',
            GC_STORAGE TYPE STRING VALUE 'STORAGE',
            GC_OTHERS  TYPE STRING VALUE 'OTHERS',
            GC_FACA    TYPE STRING VALUE 'FACA',
            GC_STRA    TYPE STRING VALUE 'STRA',
            GC_FIN_ALL TYPE STRING VALUE 'ALL'.
