*&---------------------------------------------------------------------*
*& Include          ZEA_MM040_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF SCREEN 110 AS SUBSCREEN NESTING LEVEL 1.
  SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

  SELECT-OPTIONS SO_MATNR FOR ZEA_MMT030-MATNR.
  SELECT-OPTIONS SO_WERKS FOR ZEA_MMT030-WERKS.

  SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN END OF SCREEN 110 .

PARAMETERS: B_MATNR LIKE ZEA_MMT030-MATNR NO-DISPLAY.
PARAMETERS: B_WERKS LIKE ZEA_MMT030-WERKS NO-DISPLAY.
