*&---------------------------------------------------------------------*
*& Include          ZEA_MM030_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF SCREEN 110 AS SUBSCREEN NESTING LEVEL 1.
  SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

*  PARAMETERS: P_INFON LIKE ZEA_MMT050-INFO_NO.
  SELECT-OPTIONS SO_INFON FOR ZEA_MMT050-INFO_NO.
  SELECT-OPTIONS SO_VENCO FOR ZEA_MMT050-VENCODE.
  SELECT-OPTIONS SO_WERKS FOR ZEA_MMT050-WERKS.
  SELECT-OPTIONS SO_MATNR FOR ZEA_MMT050-MATNR.

  SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN END OF SCREEN 110 .
