*&---------------------------------------------------------------------*
*& Include          ZEA_SD160_TOP
*&---------------------------------------------------------------------*

TABLES: ZEA_KNA1, ZEA_KNKK, ZEA_SDT040.

DATA: OK_CODE     TYPE SY-UCOMM,
      GV_ODAMT    TYPE ZEA_SDT040-TOAMT,
      KLIMK_EXTRA TYPE ZEA_SDT040-TOAMT,
      AR          TYPE ZEA_SDT040-TOAMT,
*      KLIMK_PERC TYPE P LENGTH 5 DECIMALS 2 .
      KLIMK_PERC  TYPE I,
      ICON        LIKE ICON-ID.

DATA: BEGIN OF GS_DATA,
        CUSCODE TYPE ZEA_KNA1-CUSCODE,  " 고객정보
        SAKNR   TYPE ZEA_KNA1-SAKNR,
        BPCUS   TYPE ZEA_KNA1-BPCUS,
        BPCSNR  TYPE ZEA_KNA1-BPCSNR,
        BPHAED  TYPE ZEA_KNA1-BPHAED,
        BPADRR  TYPE ZEA_KNA1-BPADRR,
        BPSTAT  TYPE ZEA_KNA1-BPSTAT,
        ZLSCH   TYPE ZEA_KNA1-ZLSCH,
        LAND1   TYPE ZEA_KNA1-LAND1,

        KLIMK   TYPE ZEA_KNKK-KLIMK,    " 여신정보
        WAERS   TYPE ZEA_KNKK-WAERS,
        STATUS_K  TYPE ZEA_KNKK-STATUS_K,
      END OF GS_DATA.
DATA: GT_DATA LIKE TABLE OF GS_DATA.



*** 팝업 (해당 고객 판매오더 수금 미결 내역)
DATA: BEGIN OF GS_DATA2,
        VBELN   TYPE ZEA_SDT040-VBELN,
        ODDAT   TYPE ZEA_SDT040-ODDAT,
        TOAMT   TYPE ZEA_SDT040-TOAMT,
        SADDR   TYPE ZEA_SDT040-SADDR,
        VDATU   TYPE ZEA_SDT040-VDATU,
        WAERS   TYPE ZEA_SDT040-WAERS,
        STATUS4 TYPE ZEA_SDT040-STATUS4,
        LOEKZ   TYPE ZEA_SDT040-LOEKZ,
      END OF GS_DATA2.
DATA: GT_DATA2 LIKE TABLE OF GS_DATA2.

DATA GS_DISPLAY2 LIKE LINE OF GT_DATA2.
DATA: GT_DISPLAY2 LIKE TABLE OF GS_DISPLAY2.

DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID,
      GT_FIELDCAT  TYPE LVC_T_FCAT,
      GS_FIELDCAT  TYPE LVC_S_FCAT,
      GS_LAYOUT    TYPE LVC_S_LAYO,
      GS_VARIANT   TYPE DISVARIANT,
      GV_SAVE      TYPE C.
