*&---------------------------------------------------------------------*
*& Include          YE00_EX001_TOP
*&---------------------------------------------------------------------*

" Dictionary Structure
TABLES ZEA_SDT090.


DATA: BEGIN OF GS_SDT090,
        MATNR    TYPE ZEA_SDT090-MATNR,
        WERKS    TYPE ZEA_SDT090-WERKS,
        PNAME1   TYPE ZEA_T001W-PNAME1,
        VALID_EN TYPE ZEA_SDT090-VALID_EN,
        VALID_ST TYPE ZEA_SDT090-VALID_ST,
        NETPR    TYPE ZEA_SDT090-NETPR,
        WAERS    TYPE ZEA_SDT090-WAERS,
        LOEKZ    TYPE ZEA_SDT090-LOEKZ,
        MAKTX    TYPE ZEA_MMT020-MAKTX,
      END OF GS_SDT090,
      GT_SDT090 LIKE TABLE OF GS_SDT090.


DATA: BEGIN OF GS_DISPLAY_090.
        INCLUDE STRUCTURE GS_SDT090.

DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_090.

DATA: GT_DISPLAY_090 LIKE TABLE OF GS_DISPLAY_090.




*--
* 두번째 ALV에 출력할 데이터를 보관하는 Internal Table (아래 R)
DATA: BEGIN OF GS_SDT070,
        PAYNR   TYPE ZEA_SDT070-PAYNR,
        VBELN   TYPE ZEA_SDT070-VBELN,
        ODDAT   TYPE ZEA_SDT070-ODDAT,
        INVDT   TYPE ZEA_SDT070-INVDT,
        CUSCODE TYPE ZEA_SDT070-CUSCODE,
        CHARGE  TYPE ZEA_SDT070-CHARGE,
        EATAX   TYPE ZEA_SDT070-EATAX,
        BILLAMT TYPE ZEA_SDT070-BILLAMT,
        WAERS   TYPE ZEA_SDT070-WAERS,
        ZLSCH   TYPE ZEA_SDT070-ZLSCH,
        BUKRS   TYPE ZEA_SDT070-BUKRS,
        GJAHR   TYPE ZEA_SDT070-GJAHR,
        BELNR   TYPE ZEA_SDT070-BELNR,
        STATUS  TYPE ZEA_SDT070-STATUS,
        LOEKZ   TYPE ZEA_SDT070-LOEKZ,
      END OF GS_SDT070,
      GT_SDT070 LIKE TABLE OF GS_SDT070.


DATA: BEGIN OF GS_DISPLAY_070.
        INCLUDE STRUCTURE GS_SDT070.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_070.

DATA: GT_DISPLAY_070 LIKE TABLE OF GS_DISPLAY_070.



*--
* 세번째 ALV에 출력할 데이터를 보관하는 Internal Table (아래 L)
DATA: BEGIN OF GS_SDT120,
        PAYNR  TYPE ZEA_SDT120-PAYNR,
        POSNR  TYPE ZEA_SDT120-POSNR,
        MATNR  TYPE ZEA_SDT120-MATNR,
        MAKTX  TYPE ZEA_MMT020-MAKTX,
        AUQUA  TYPE ZEA_SDT120-AUQUA,
        MEINS  TYPE ZEA_SDT120-MEINS,
        NETPR  TYPE ZEA_SDT120-NETPR,
        WAERS  TYPE ZEA_SDT120-WAERS,
        BPNAME TYPE ZEA_SKA1-BPNAME,
        BPROLE TYPE ZEA_SKA1-BPROLE,
      END OF GS_SDT120,
      GT_SDT120 LIKE TABLE OF GS_SDT120.

DATA: BEGIN OF GS_DISPLAY_120.
        INCLUDE STRUCTURE GS_SDT120.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_120.

DATA: GT_DISPLAY_120 LIKE TABLE OF GS_DISPLAY_120.


DATA: BEGIN OF GS_MMT010,
        MATNR   TYPE ZEA_MMT010-MATNR,
        MAKTX   TYPE ZEA_MMT020-MAKTX,
        MATTYPE TYPE ZEA_MMT010-MATTYPE,
        MATGRP  TYPE ZEA_MMT010-MATGRP,
        BSTME   TYPE ZEA_MMT010-BSTME,
        MEINS2  TYPE ZEA_MMT010-MEINS2,
        WEIGHT  TYPE ZEA_MMT010-WEIGHT,
        MEINS1  TYPE ZEA_MMT010-MEINS1,
        LOEKZ   TYPE ZEA_MMT010-LOEKZ,
        STPRS   TYPE ZEA_MMT010-STPRS,
        WAERS   TYPE ZEA_MMT010-WAERS,
      END OF GS_MMT010.

DATA: BEGIN OF GS_DISPLAY_010.
        INCLUDE STRUCTURE GS_MMT010.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_010.

DATA: GT_DISPLAY_010 LIKE TABLE OF GS_DISPLAY_010.


* 화면 관련 변수
DATA: OK_CODE      TYPE SY-UCOMM.

* 화면에 데이터를 출력하기 위한 참조변수
DATA: GO_CONTAINER      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_SPLIT          TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GO_CON_TOP_L      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_TOP_R      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_BOT_L      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_BOT_R      TYPE REF TO CL_GUI_CONTAINER,
      GO_ALV_GRID_TOP_L   TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_TOP_R TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_BOT_L TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_BOT_R TYPE REF TO CL_GUI_ALV_GRID.


* ALV 관련 변수
DATA: GS_LAYOUT       TYPE LVC_S_LAYO,
      GT_FIELDCAT_090 TYPE LVC_T_FCAT,
      GS_FIELDCAT_090 TYPE LVC_S_FCAT,
      GT_FIELDCAT_070 TYPE LVC_T_FCAT,
      GS_FIELDCAT_070 TYPE LVC_S_FCAT,
      GT_FIELDCAT_120 TYPE LVC_T_FCAT,
      GS_FIELDCAT_120 TYPE LVC_S_FCAT,
      GT_FIELDCAT_010 TYPE LVC_T_FCAT,
      GS_FIELDCAT_010 TYPE LVC_S_FCAT,
      GS_VARIANT      TYPE DISVARIANT,
      GV_SAVE         TYPE C.
