*&---------------------------------------------------------------------*
*& Include          ZEA_TR_TEM2_TOP
*&---------------------------------------------------------------------*

CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.

TABLES : ZEA_T001W, ZEA_PPT010, ZEA_MMT020.

DATA : BEGIN OF gs_ZEA_T001W.
         INCLUDE STRUCTURE zea_t001W.
DATA :   NODE_KEY TYPE I,
         MATNR    TYPE ZEA_PPT010-MATNR,
       END OF gs_ZEA_T001W,

       GT_ZEA_T001W  LIKE TABLE OF GS_ZEA_T001W,
       GS_ZEA_PPT010 TYPE ZEA_PPT010,
       GT_ZEA_PPT010 TYPE TABLE OF ZEA_PPT010.

DATA : GS_NODE  TYPE MTREESNODE,
       GT_NODE  LIKE TABLE OF GS_NODE,
       OK_CODE  TYPE SY-UCOMM,
       GT_EVENT TYPE CNTL_SIMPLE_EVENTS,
       GS_EVENT LIKE LINE OF GT_EVENT,
       GV_NODE  TYPE I.

DATA : GCL_CONTAINER       TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GCL_SPLITTER        TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
       GCL_HANDLER         TYPE REF TO LCL_EVENT_HANDLER,
       GCL_CONTAINER_LEFT  TYPE REF TO CL_GUI_CONTAINER,
       GCL_CONTAINER_RIGHT TYPE REF TO CL_GUI_CONTAINER,
       GCL_GRID            TYPE REF TO CL_GUI_ALV_GRID,
       GCL_TREE            TYPE REF TO CL_GUI_SIMPLE_TREE,
       GS_FCAT             TYPE LVC_S_FCAT,
       GT_FCAT             TYPE LVC_T_FCAT,
       GS_LAYOUT           TYPE LVC_S_LAYO,
       GS_VARAINT          TYPE DISVARIANT,
       GS_STABLE           TYPE LVC_S_STBL.
