FUNCTION-POOL ZEA_MM_FG.                    "MESSAGE-ID ..

* INCLUDE LZEA_MM_FGD...                     " Local class definition

TABLES: ZEA_AUFK, ZEA_PPT020, ZEA_MMT140, ZEA_MMT150, ZEA_MMT090,
        ZEA_AFRU, ZEA_MMT100, ZEA_MMT010, ZEA_SDT110, ZEA_STPO,
        ZEA_MMT070, ZEA_MMT190.

DATA: GT_AUFK TYPE TABLE OF ZEA_AUFK,
      GS_AUFK TYPE ZEA_AUFK.

DATA: GT_PPT020 TYPE TABLE OF ZEA_PPT020,
      GS_PPT020 TYPE ZEA_PPT020.

  DATA: BEGIN OF GS_DATA,
        AUFNR   TYPE ZEA_AFRU-AUFNR,
        CHARG   TYPE ZEA_AFRU-CHARG,
        MATNR   TYPE ZEA_AFRU-MATNR,
        BOMID   TYPE ZEA_AFRU-BOMID,
        EMPCODE TYPE ZEA_AFRU-EMPCODE,
        WERKS   TYPE ZEA_MMT070-WERKS,
        SCODE  TYPE ZEA_MMT070-SCODE,
        TSDAT   TYPE ZEA_AFRU-TSDAT,
        FNPD    TYPE ZEA_AFRU-FNPD,
        MEINS   TYPE ZEA_AFRU-MEINS,
      END OF GS_DATA.

DATA GT_DATA LIKE TABLE OF GS_DATA.

* [SD]
DATA: GT_SDT060 TYPE TABLE OF ZEA_SDT060,
      GS_SDT060 TYPE          ZEA_SDT060.
DATA: GT_SDT110 TYPE TABLE OF ZEA_SDT110,
      GS_SDT110 TYPE          ZEA_SDT110.

* [MM]
DATA: GT_MMT140 TYPE TABLE OF ZEA_MMT140,
      GS_MMT140 TYPE          ZEA_MMT140.
DATA: GT_MMT150 TYPE TABLE OF ZEA_MMT150,
      GS_MMT150 TYPE          ZEA_MMT150.

* 자재문서
DATA : GT_MMT090 TYPE TABLE OF ZEA_MMT090 WITH HEADER LINE.
DATA: GS_MMT090 LIKE LINE OF GT_MMT090.
DATA : GT_MMT100 TYPE TABLE OF ZEA_MMT100 WITH HEADER LINE.

DATA: GT_MMT190 TYPE TABLE OF ZEA_MMT190,
      GS_MMT190 TYPE ZEA_MMT190.
DATA: GT_MMT070 TYPE TABLE OF ZEA_MMT070,
      GS_MMT070 TYPE ZEA_MMT070.
