FUNCTION ZEA_MM_TRF.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_PLANTFR) TYPE  ZEA_MMT190-WERKS
*"     REFERENCE(IV_PLANTTO) TYPE  ZEA_MMT190-WERKS
*"     REFERENCE(IV_MATNR) TYPE  ZEA_MMT190-MATNR
*"     REFERENCE(IV_QUANTITY) TYPE  ZEA_MMT190-CALQTY
*"  EXPORTING
*"     REFERENCE(ES_HEAD) TYPE  ZEA_MMT090
*"     REFERENCE(ET_ITEM) TYPE  ZEA_MMY100
*"----------------------------------------------------------------------
* 삭제 플레그 WHERE절 추가 해줘야됨 ZEA_MMT190, ZEA_MMT070.

  DATA: LS_MMT070_OUT TYPE ZEA_MMT070,
        LS_MMT070_IN  TYPE ZEA_MMT070.

  DATA: LS_MMT190_OUT TYPE ZEA_MMT190,
        LS_MMT190_IN  TYPE ZEA_MMT190.


  DATA: LV_AFTERQTY    TYPE ZEA_MMT070-CALQTY,
        LV_AFTERCALQTY TYPE ZEA_MMT070-CALQTY,
        LV_AFTERREMQTY TYPE ZEA_MMT070-REMQTY.

  SELECT SINGLE STPRS
    FROM ZEA_MMT010
    INTO @DATA(LV_STPRS)
    WHERE MATNR EQ @IV_MATNR.


  SELECT SINGLE MATNR, WERKS, MIN( CHARG ) AS CHARG , SCODE, CALQTY, REMQTY, MEINS
    FROM ZEA_MMT070
   WHERE WERKS EQ @IV_PLANTFR
     AND MATNR EQ @IV_MATNR
     AND LVORM EQ @SPACE
    GROUP BY MATNR, WERKS, SCODE, CALQTY, REMQTY, MEINS
    INTO CORRESPONDING FIELDS OF @LS_MMT070_OUT.

  IF IV_QUANTITY > LS_MMT070_OUT-REMQTY.
    MESSAGE  |출고 수량이 잔여 수량보다 많습니다.| TYPE 'S' DISPLAY LIKE 'E'.
    EXIT.
  ELSEIF IV_QUANTITY = LS_MMT070_OUT-REMQTY.
    " 출고 창고의 수량 업데이트
    UPDATE ZEA_MMT070 SET REMQTY = 0 LVORM = 'X' WHERE MATNR EQ LS_MMT070_OUT-MATNR
                                                 AND WERKS   EQ LS_MMT070_OUT-WERKS
                                                 AND CHARG   EQ LS_MMT070_OUT-CHARG.

    UPDATE ZEA_MMT190 SET CALQTY = 0 WHERE MATNR EQ LS_MMT070_OUT-MATNR
                                       AND WERKS EQ LS_MMT070_OUT-WERKS.

  ELSE.
    " 출고 창고의 수량 업데이트
    LV_AFTERQTY = LS_MMT070_OUT-REMQTY - IV_QUANTITY.

    UPDATE ZEA_MMT070 SET REMQTY = LV_AFTERQTY WHERE MATNR EQ LS_MMT070_OUT-MATNR
                                                 AND WERKS EQ LS_MMT070_OUT-WERKS
                                                 AND CHARG EQ LS_MMT070_OUT-CHARG.

    SELECT SINGLE *
      FROM ZEA_MMT190
      WHERE MATNR EQ @LS_MMT070_OUT-MATNR
        AND WERKS EQ @LS_MMT070_OUT-WERKS
      INTO CORRESPONDING FIELDS OF @LS_MMT190_OUT.

    DATA LV_CALQTY TYPE ZEA_MMT190-CALQTY.
    LV_CALQTY = LS_MMT190_OUT-CALQTY - IV_QUANTITY.

    UPDATE ZEA_MMT190 SET CALQTY = LV_CALQTY
                    WHERE MATNR EQ LS_MMT070_OUT-MATNR
                      AND WERKS EQ LS_MMT070_OUT-WERKS.

  ENDIF.

  " 입고 창고의 수량 업데이트
  " LS_MMT070_OUT : MATNR, WERKS, MIN( CHARG ) AS CHARG , SCODE, CALQTY, REMQTY, MEINS

  SELECT SINGLE SCODE
    FROM ZEA_MMT060
   WHERE WERKS EQ @IV_PLANTTO
    INTO @DATA(LV_SCODE).

  MOVE-CORRESPONDING LS_MMT070_OUT TO LS_MMT070_IN.
  LS_MMT070_IN-WERKS  = IV_PLANTTO.
  LS_MMT070_IN-SCODE  = LV_SCODE.
  LS_MMT070_IN-REMQTY = IV_QUANTITY.

  SELECT SINGLE REMQTY
    FROM ZEA_MMT070
   WHERE MATNR EQ @LS_MMT070_IN-MATNR
     AND WERKS EQ @LS_MMT070_IN-WERKS
     AND CHARG EQ @LS_MMT070_IN-CHARG
     INTO @DATA(LV_REMQTY).

  IF SY-SUBRC NE 0.
    INSERT ZEA_MMT070 FROM LS_MMT070_IN.
  ELSE.
    LV_AFTERREMQTY = LV_REMQTY + IV_QUANTITY.

    UPDATE ZEA_MMT070 SET REMQTY = LV_AFTERREMQTY
                    WHERE MATNR EQ LS_MMT070_IN-MATNR
                      AND WERKS EQ LS_MMT070_IN-WERKS
                      AND CHARG EQ LS_MMT070_IN-CHARG.
  ENDIF.

  SELECT SINGLE *
    FROM ZEA_MMT190
    WHERE MATNR  EQ @IV_MATNR
      AND WERKS  EQ @IV_PLANTTO
      AND SCODE  EQ @LV_SCODE
    INTO CORRESPONDING FIELDS OF @LS_MMT190_IN.

  IF SY-SUBRC EQ 0.
    LV_CALQTY = LS_MMT190_IN-CALQTY + IV_QUANTITY.

    UPDATE ZEA_MMT190 SET CALQTY = LV_CALQTY
                      WHERE MATNR EQ LS_MMT190_IN-MATNR
                        AND WERKS EQ LS_MMT190_IN-WERKS
                        AND SCODE EQ LS_MMT190_IN-SCODE.
  ELSE.

    CLEAR LS_MMT190_IN.
    LS_MMT190_IN-MATNR   = IV_MATNR.
    LS_MMT190_IN-WERKS   = IV_PLANTTO.
    LS_MMT190_IN-SCODE   = LV_SCODE.
    LS_MMT190_IN-CALQTY  = IV_QUANTITY.
    LS_MMT190_IN-MEINS   = LS_MMT070_IN-MEINS.
*      LS_MMT190_IN-WEIGHT
*      LS_MMT190_IN-MEINS2
*      LS_MMT190_IN-SAFSTK
*      LS_MMT190_IN-MEINS3

    INSERT ZEA_MMT190 FROM LS_MMT190_IN.
  ENDIF  .

  " 헤더 트랜젝션유형: 재고이동

  DATA : NR_RANGE_NR  LIKE  INRI-NRRANGENR.
  DATA : OBJECT       LIKE  INRI-OBJECT.
  DATA : QUANTITY     LIKE  INRI-QUANTITY.
  DATA : GV_NUM       TYPE  I.

  CLEAR: NR_RANGE_NR, OBJECT, QUANTITY.
  NR_RANGE_NR = '07'.
  OBJECT      = 'ZEA_MMNR'.
  QUANTITY    = 1.

  CALL FUNCTION 'NUMBER_GET_NEXT'
    EXPORTING
      NR_RANGE_NR             = NR_RANGE_NR
      OBJECT                  = OBJECT
      QUANTITY                = QUANTITY
    IMPORTING
      NUMBER                  = GS_MMT090-MBLNR "PV_MBLNR
    EXCEPTIONS
      INTERVAL_NOT_FOUND      = 1
      NUMBER_RANGE_NOT_INTERN = 2
      OBJECT_NOT_FOUND        = 3
      QUANTITY_IS_0           = 4
      QUANTITY_IS_NOT_1       = 5
      INTERVAL_OVERFLOW       = 6
      BUFFER_OVERFLOW         = 7
      OTHERS                  = 8.


  "자재문서번호
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
    EXPORTING
      INPUT  = GS_MMT090-MBLNR  " PV_MBLNR
    IMPORTING
      OUTPUT = GT_MMT090-MBLNR. " PV_MBLNR.


  GT_MMT090-GJAHR = SY-DATUM(4).   "회계연도
  GT_MMT090-WERKS = IV_PLANTFR.  "플랜트
  GT_MMT090-BUDAT = SY-DATUM(8).  "전기일
 GT_MMT090-ERNAM = SY-UNAME.
 GT_MMT090-ERDAT = SY-DATUM.
 GT_MMT090-ERZET = SY-UZEIT.
 APPEND GT_MMT090.

  MODIFY ZEA_MMT090 FROM  GT_MMT090.
  IF SY-SUBRC NE 0.
    ROLLBACK WORK.
    EXIT.
  ENDIF.

   ES_HEAD = GT_MMT090.

  " 출고 문서 / 이동유형 311
  CLEAR: GT_MMT100.
  GT_MMT100-MBLNR = GT_MMT090-MBLNR.
  GT_MMT100-GJAHR = SY-DATUM(4).
  GT_MMT100-MBGNO = 1.
  GT_MMT100-MATNR = IV_MATNR.
  GT_MMT100-CHARG = LS_MMT070_OUT-CHARG.
  GT_MMT100-BWART = '311'.
  GT_MMT100-PLANTFR = IV_PLANTFR.
  GT_MMT100-LGORTFR = LS_MMT070_OUT-SCODE.
  GT_MMT100-PLANTTO = IV_PLANTTO.
  GT_MMT100-LGORTTO = LS_MMT070_IN-SCODE.
  GT_MMT100-MENGE = - IV_QUANTITY.
  GT_MMT100-MEINS = LS_MMT070_OUT-MEINS.
  GT_MMT100-DMBTR = LV_STPRS * - IV_QUANTITY.
  GT_MMT100-WAERS1 = 'KRW'.
  GT_MMT100-VENCODE = SPACE.
  GT_MMT100-GRUND = '재고이전 출발'.
  GT_MMT100-ERNAM = SY-UNAME.
  GT_MMT100-ERDAT = SY-DATUM.
  GT_MMT100-ERZET = SY-UZEIT.
  APPEND GT_MMT100 .

  " 입고 문서 / 이동유형 311
  CLEAR: GT_MMT100.
  GT_MMT100-MBLNR = GT_MMT090-MBLNR.
  GT_MMT100-GJAHR = SY-DATUM(4).
  GT_MMT100-MBGNO = 2.
  GT_MMT100-MATNR = IV_MATNR.
  GT_MMT100-CHARG = LS_MMT070_IN-CHARG.
  GT_MMT100-BWART = '311'.
  GT_MMT100-PLANTFR = IV_PLANTFR.
  GT_MMT100-LGORTFR = LS_MMT070_OUT-SCODE.
  GT_MMT100-PLANTTO = IV_PLANTTO.
  GT_MMT100-LGORTTO = LS_MMT070_IN-SCODE.
  GT_MMT100-MENGE = IV_QUANTITY.
  GT_MMT100-MEINS = LS_MMT070_OUT-MEINS.
  GT_MMT100-DMBTR = LV_STPRS * IV_QUANTITY.
  GT_MMT100-WAERS1 = 'KRW'.
  GT_MMT100-VENCODE = SPACE.
  GT_MMT100-GRUND = '재고이전 도착'.
  GT_MMT100-ERNAM = SY-UNAME.
  GT_MMT100-ERDAT = SY-DATUM.
  GT_MMT100-ERZET = SY-UZEIT.
  APPEND GT_MMT100 .

  MODIFY ZEA_MMT100 FROM TABLE GT_MMT100.
  IF SY-SUBRC NE 0.
    ROLLBACK WORK.
  ENDIF.

 ET_ITEM = GT_MMT100[].

ENDFUNCTION.
