*&---------------------------------------------------------------------*
*& Include          YE00_EX007TOP
*&---------------------------------------------------------------------*

TABLES: ZEA_T001W, ZEA_MDKP, ZEA_MDTB.

CONSTANTS: GC_MRP_CALC  TYPE STRING VALUE 'MRP_CALC',
           GC_MRP_MONTH TYPE STRING VALUE 'MRP_MONTH',
           GC_NO_FILTER TYPE STRING VALUE 'NO_FILTER',
           GC_FIN       TYPE STRING VALUE 'FIN',
           GC_SEMI      TYPE STRING VALUE 'SEMI',
           GC_RAW       TYPE STRING VALUE 'RAW',
           GC_BACK      TYPE STRING VALUE 'BACK'.

*-- Database Table에서 조회 후 출력을 위한 Internal Tables
DATA: BEGIN OF GS_HEADER,
        PDPDAT LIKE ZEA_PLAF-PDPDAT,
        BUKRS  LIKE ZEA_T001W-BUKRS,
*        WERKS_PROD LIKE ZEA_T001W-WERKS,
        WERKS  LIKE ZEA_T001W-WERKS,
        PNAME1 LIKE ZEA_T001W-PNAME1,
        MATNR  LIKE ZEA_SDT030-MATNR,
        MAKTX  LIKE ZEA_MMT020-MAKTX,
      END OF GS_HEADER,
      GT_HEADER LIKE TABLE OF GS_HEADER.

DATA: BEGIN OF GS_DISPLAY,
        PLANID    LIKE ZEA_PPT010-PLANID,
        PLANINDEX LIKE ZEA_PPT010-PLANINDEX,
        MATNR     LIKE ZEA_PPT010-MATNR,
        MAKTX     LIKE ZEA_MMT020-MAKTX,
        BOMID     LIKE ZEA_PPT010-BOMID,
        PLANQTY1  LIKE ZEA_PPT010-PLANQTY1,
        PLANQTY2  LIKE ZEA_PPT010-PLANQTY2,
        PLANQTY3  LIKE ZEA_PPT010-PLANQTY3,
        PLANQTY4  LIKE ZEA_PPT010-PLANQTY4,
        PLANQTY5  LIKE ZEA_PPT010-PLANQTY5,
        PLANQTY6  LIKE ZEA_PPT010-PLANQTY6,
        PLANQTY7  LIKE ZEA_PPT010-PLANQTY7,
        PLANQTY8  LIKE ZEA_PPT010-PLANQTY8,
        PLANQTY9  LIKE ZEA_PPT010-PLANQTY9,
        PLANQTY10 LIKE ZEA_PPT010-PLANQTY10,
        PLANQTY11 LIKE ZEA_PPT010-PLANQTY11,
        PLANQTY12 LIKE ZEA_PPT010-PLANQTY12,
        TOTAL     TYPE ZEA_PPT010-PLANQTY1,
        MEINS     LIKE ZEA_PPT010-MEINS,
*        LIGHT     TYPE C,
      END OF GS_DISPLAY,

      GT_DISPLAY LIKE TABLE OF GS_DISPLAY.


DATA: BEGIN OF GS_STKO,
        BOMID   TYPE ZEA_STKO-BOMID,
        WERKS   TYPE ZEA_STKO-WERKS,
        MATNR   TYPE ZEA_STKO-MATNR,
        MAKTX   TYPE ZEA_MMT020-MAKTX,
        MATTYPE TYPE ZEA_MMT010-MATTYPE,
        MENGE   TYPE ZEA_STKO-MENGE,
        MEINS   TYPE ZEA_STKO-MEINS,
        LOEKZ   TYPE ZEA_STKO-LOEKZ,
      END OF GS_STKO.

DATA: GT_STKO LIKE TABLE OF GS_STKO.

DATA: BEGIN OF GS_STKO_DISPLAY.
        INCLUDE STRUCTURE GS_STKO.
DATA:   STATUS          LIKE ICON-ID, " 아이콘
        COLOR           TYPE C LENGTH 4, " 행 색상 정보
        LIGHT           TYPE C,          " 신호등 표시를 위한
        " EXCEPTION 필드
        " 0:비움 1:빨강 2:노랑 3:초록
        IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
        STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
        MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_STKO_DISPLAY.

DATA: GT_STKO_DISPLAY LIKE TABLE OF GS_STKO_DISPLAY,
      GT_STKO_CP      LIKE TABLE OF GS_STKO_DISPLAY,
      GS_STKO_CP      LIKE LINE OF GT_STKO_CP.

DATA : BEGIN OF GS_STPO, "MRP 계산을 위한 인터널 테이블
         BOMID    TYPE ZEA_STPO-BOMID,
         BOMINDEX TYPE ZEA_STPO-BOMINDEX,
         BOMID2   TYPE ZEA_STPO-BOMID,
         MATNR    TYPE ZEA_STPO-MATNR,
         MAKTX    TYPE ZEA_MMT020-MAKTX,
         MATTYPE  TYPE ZEA_MMT010-MATTYPE,
         MENGE    TYPE ZEA_STPO-MENGE,
         MEINS    TYPE ZEA_STPO-MEINS,
       END OF GS_STPO.

DATA: GT_STPO LIKE TABLE OF GS_STPO.

DATA: BEGIN OF GS_STPO_DISPLAY.
        INCLUDE STRUCTURE GS_STPO.
DATA:   STATUS          LIKE ICON-ID, " 아이콘
        COLOR           TYPE C LENGTH 4, " 행 색상 정보
        LIGHT           TYPE C,          " 신호등 표시를 위한
        " EXCEPTION 필드
        " 0:비움 1:빨강 2:노랑 3:초록
        IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
        STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
        MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_STPO_DISPLAY.

DATA: GS_FIELD_COLOR TYPE LVC_S_SCOL.

DATA: GT_STPO_DISPLAY LIKE TABLE OF GS_STPO_DISPLAY,
      GT_STPO_CP      LIKE TABLE OF GS_STPO_DISPLAY,
      GS_STPO_CP      LIKE LINE OF  GT_STPO_CP.

DATA : BEGIN OF GS_COLLECT,
*               BOMID   TYPE ZEA_STPO-BOMID,
         MATNR   TYPE ZEA_STPO-MATNR,
         MAKTX   TYPE ZEA_MMT020-MAKTX,
         MATTYPE TYPE ZEA_MMT010-MATTYPE,
         STOCK   TYPE ZEA_MDTB-STOCK,
         MENGE   TYPE ZEA_STPO-MENGE,
         REQQTY  TYPE ZEA_MDTB-REQQTY,
         MEINS   TYPE ZEA_STPO-MEINS,
       END OF GS_COLLECT.

DATA GT_COLLECT LIKE TABLE OF GS_COLLECT.

DATA : BEGIN OF GS_COLLECT_DISPLAY.
        INCLUDE STRUCTURE GS_COLLECT.
DATA : IT_FIELD_COLORS TYPE LVC_T_SCOL,
      END OF GS_COLLECT_DISPLAY.

DATA: GT_COLLECT_DISPLAY LIKE TABLE OF GS_COLLECT_DISPLAY.

DATA: BEGIN OF TS_ZEA_MDKP,
        MRPID TYPE ZEA_MDKP-MRPID,
      END OF TS_ZEA_MDKP.

" MRP 계산 결과 HEADER
*  DATA: BEGIN OF GS_ZEA_MDKP,
*          MRPID  TYPE ZEA_MDKP-MRPID,
*          WERKS  TYPE ZEA_MDKP-WERKS,
*          PLANID TYPE ZEA_MDKP-PLANID,
*          PDPDAT TYPE ZEA_MDKP-PDPDAT,
*          PDPMON TYPE ZEA_MDKP-PDPMON,
*          LOEKZ  TYPE ZEA_MDKP-LOEKZ,
*          ERNAM  TYPE ZEA_MDKP-ERNAM,
*          ERDAT  TYPE ZEA_MDKP-ERDAT,
*          ERZET  TYPE ZEA_MDKP-ERZET,
*          AENAM  TYPE ZEA_MDKP-AENAM,
*          AEDAT  TYPE ZEA_MDKP-AEDAT,
*          AEZET  TYPE ZEA_MDKP-AEZET,
*        END OF GS_ZEA_MDKP,
DATA: GS_ZEA_MDKP TYPE ZEA_MDKP,
      GT_ZEA_MDKP LIKE TABLE OF GS_ZEA_MDKP.

" MRP 계산 결과 ITEM
*DATA: BEGIN OF GS_ZEA_MDTB,
*        MRPID     TYPE ZEA_MDTB-MRPID,
*        MATNR     TYPE ZEA_MDTB-MATNR,
*        STOCK     TYPE ZEA_MDTB-STOCK,
*        USEQTY    TYPE ZEA_MDTB-USEQTY,
*        REQQTY    TYPE ZEA_MDTB-REQQTY,
*        MEINS     TYPE ZEA_MDTB-MEINS,
*        PLANSDATE TYPE ZEA_MDTB-PLANSDATE,
*        PLANEDATE TYPE ZEA_MDTB-PLANEDATE,
*        LOEKZ     TYPE ZEA_MDTB-LOEKZ,
*        ERNAM     TYPE ZEA_MDTB-ERNAM,
*        ERDAT     TYPE ZEA_MDTB-ERDAT,
*        ERZET     TYPE ZEA_MDTB-ERZET,
*        AENAM     TYPE ZEA_MDTB-AENAM,
*        AEDAT     TYPE ZEA_MDTB-AEDAT,
*        AEZET     TYPE ZEA_MDTB-AEZET,
*      END OF GS_ZEA_MDTB,
DATA: GS_ZEA_MDTB TYPE ZEA_MDTB,
      GT_ZEA_MDTB LIKE TABLE OF GS_ZEA_MDTB.


*-- SCREEN 관련 변수
CONSTANTS: GC_CUSTOM_CONTAINER_NAME TYPE SCRFNAME VALUE 'CCON'.
CONSTANTS: GC_CUSTOM_CONTAINER_NAME2 TYPE SCRFNAME VALUE 'CCON2'.
CONSTANTS: GC_CUSTOM_CONTAINER_NAME4 TYPE SCRFNAME VALUE 'CCON4'.
DATA: OK_CODE TYPE SY-UCOMM.

DATA: BEGIN OF S0110,
        DATEFROM TYPE DATS,
        DATETO   TYPE DATS,
      END OF S0110.


*-- TREE ALV
DATA: GO_DOCKING_CONTAINER TYPE REF TO CL_GUI_DOCKING_CONTAINER,
      GO_CUSTOM_CONTAINER  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

      GO_CUSTOM_CONTAINER2 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_CUSTOM_CONTAINER4 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_SPLIT             TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GO_CON_LEFT          TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_RIGHT         TYPE REF TO CL_GUI_CONTAINER,
      GO_ALV_GRID_LEFT     TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_RIGHT    TYPE REF TO CL_GUI_ALV_GRID,

      GO_SIMPLE_TREE       TYPE REF TO CL_GUI_SIMPLE_TREE,
      GO_ALV_GRID          TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID4         TYPE REF TO CL_GUI_ALV_GRID.

*-- ALV 관련 변수
DATA: GS_LAYOUT     TYPE LVC_S_LAYO,
      GS_LAYOUT2    TYPE LVC_S_LAYO,
      GS_LAYOUT3    TYPE LVC_S_LAYO,
      GS_LAYOUT4    TYPE LVC_S_LAYO,
      GT_FIELDCAT   TYPE LVC_T_FCAT,
      GT_FIELDCAT2  TYPE LVC_T_FCAT,
      GT_FIELDCAT3  TYPE LVC_T_FCAT,
      GT_FIELDCAT4  TYPE LVC_T_FCAT,
      GS_FIELDCAT   LIKE LINE OF GT_FIELDCAT,
      GS_FIELDCAT2  LIKE LINE OF GT_FIELDCAT,
      GS_FIELDCAT3  LIKE LINE OF GT_FIELDCAT,
      GS_FIELDCAT4  LIKE LINE OF GT_FIELDCAT,
      GT_SORT       TYPE LVC_T_SORT,
      GS_SORT       LIKE LINE OF GT_SORT,
      GS_VARIANT    TYPE DISVARIANT,
      GT_FILTER     TYPE LVC_T_FILT,
      GS_FILTER     TYPE LVC_S_FILT,
      GT_INDEX_ROWS TYPE LVC_T_ROW,
      GS_INDEX_ROW  TYPE LVC_S_ROW,
      GV_SAVE       TYPE C,
      GV_CHECK      TYPE C,
      GV_YEAR       TYPE C LENGTH 4,
      GV_MONTH      TYPE NUMC2,
      GV_YEAR2      TYPE C LENGTH 4,
      GV_MONTH2     TYPE NUMC2.

*-- TREE 관련 변수
DATA: BEGIN OF GS_NODE,
        NODE_KEY   TYPE MTREESNODE-NODE_KEY,
        RELATKEY   TYPE MTREESNODE-RELATKEY,
        RELATSHIP  TYPE MTREESNODE-RELATSHIP,
        HIDDEN     TYPE MTREESNODE-HIDDEN,
        DISABLED   TYPE MTREESNODE-DISABLED,
        ISFOLDER   TYPE MTREESNODE-ISFOLDER,
        N_IMAGE    TYPE MTREESNODE-N_IMAGE,
        EXP_IMAGE  TYPE MTREESNODE-EXP_IMAGE,
        STYLE      TYPE MTREESNODE-STYLE,
        LAST_HITEM TYPE MTREESNODE-LAST_HITEM,
        NO_BRANCH  TYPE MTREESNODE-NO_BRANCH,
        EXPANDER   TYPE MTREESNODE-EXPANDER,
        DRAGDROPID TYPE MTREESNODE-DRAGDROPID,
        TEXT       TYPE CHAR60,
      END OF GS_NODE.


DATA: GT_NODE     LIKE TABLE OF GS_NODE,
*      GS_NODE     LIKE LINE OF GT_NODE,
      GV_NODE_KEY TYPE N LENGTH 6.

DATA: BEGIN OF GS_NODE_INFO,
        NODE_KEY LIKE MTREESNODE-NODE_KEY,
        PDPDAT   LIKE ZEA_PLAF-PDPDAT,
        BUKRS    LIKE ZEA_T001W-BUKRS,
*        WERKS_PROD LIKE ZEA_T001W-WERKS,
        WERKS    LIKE ZEA_T001W-WERKS,
        PNAME1   LIKE ZEA_T001W-PNAME1,
        MATNR    LIKE ZEA_SDT030-MATNR,
        MAKTX    LIKE ZEA_MMT020-MAKTX,
      END OF GS_NODE_INFO,

      GT_NODE_INFO LIKE TABLE OF GS_NODE_INFO.


*----------------------------------------------------------------------*
* Common MACRO
*----------------------------------------------------------------------*
DEFINE _MC_POPUP_CONFIRM.
  CALL FUNCTION 'POPUP_TO_CONFIRM'
    EXPORTING
      TITLEBAR              = &1
*      DISPLAY_CANCEL_BUTTON = ''
      TEXT_QUESTION         = &2
      TEXT_BUTTON_1         = 'YES'
      ICON_BUTTON_1         = '@2K@'
      TEXT_BUTTON_2         = 'NO'
      ICON_BUTTON_2         = '@2O@ '
    IMPORTING
      ANSWER                = &3
    EXCEPTIONS
      TEXT_NOT_FOUND        = 1
      OTHERS                = 2.
END-OF-DEFINITION.
