*&---------------------------------------------------------------------*
*& Include          YE00_EX007TOP
*&---------------------------------------------------------------------*

CONSTANTS: GC_NO_FILTER TYPE STRING VALUE 'NO_FILTER',
           GC_EXIST     TYPE STRING VALUE 'EXIST',
           GC_NO_EXIST  TYPE STRING VALUE 'NO_EXIST',
           GC_CREATE    TYPE STRING VALUE 'CREATE'.

*-- Database Table에서 조회 후 출력을 위한 Internal Tables
DATA: BEGIN OF GS_HEADER,
        BUKRS  LIKE ZEA_T001W-BUKRS,
        WERKS  LIKE ZEA_T001W-WERKS,
        PNAME1 LIKE ZEA_T001W-PNAME1,
        PDPDAT LIKE ZEA_PLAF-PDPDAT,
        MATNR  LIKE ZEA_PPT010-MATNR,
        MAKTX  LIKE ZEA_MMT020-MAKTX,
      END OF GS_HEADER,
      GT_HEADER LIKE TABLE OF GS_HEADER.

DATA: BEGIN OF GS_DISPLAY,
        PLANID    LIKE ZEA_PPT010-PLANID,
        PLANINDEX LIKE ZEA_PPT010-PLANINDEX,
        MATNR     LIKE ZEA_PPT010-MATNR,
        MAKTX     LIKE ZEA_MMT020-MAKTX,
        BOMID     LIKE ZEA_PPT010-BOMID,
        PLANQTY1  LIKE ZEA_PPT010-PLANQTY1,
        PLANQTY2  LIKE ZEA_PPT010-PLANQTY2,
        PLANQTY3  LIKE ZEA_PPT010-PLANQTY3,
        PLANQTY4  LIKE ZEA_PPT010-PLANQTY4,
        PLANQTY5  LIKE ZEA_PPT010-PLANQTY5,
        PLANQTY6  LIKE ZEA_PPT010-PLANQTY6,
        PLANQTY7  LIKE ZEA_PPT010-PLANQTY7,
        PLANQTY8  LIKE ZEA_PPT010-PLANQTY8,
        PLANQTY9  LIKE ZEA_PPT010-PLANQTY9,
        PLANQTY10 LIKE ZEA_PPT010-PLANQTY10,
        PLANQTY11 LIKE ZEA_PPT010-PLANQTY11,
        PLANQTY12 LIKE ZEA_PPT010-PLANQTY12,
        TOTAL     TYPE ZEA_PPT010-PLANQTY1,
        MEINS     LIKE ZEA_PPT010-MEINS,
        LIGHT     TYPE C,
      END OF GS_DISPLAY,

      GT_DISPLAY LIKE TABLE OF GS_DISPLAY.

DATA: BEGIN OF GS_DATA,
        AUFNR     TYPE ZEA_AUFK-AUFNR,
        WERKS     TYPE ZEA_AUFK-WERKS,
        PLANID    TYPE ZEA_AUFK-PLANID,
        PNAME1    TYPE ZEA_T001W-PNAME1,
        MATNR     TYPE ZEA_AUFK-MATNR,
        MAKTX     TYPE ZEA_MMT020-MAKTX,
        TOT_QTY   TYPE ZEA_AUFK-TOT_QTY,
        MEINS     TYPE ZEA_AUFK-MEINS,
        APPROVAL  TYPE ZEA_AUFK-APPROVAL,
        APPROVER  TYPE ZEA_AUFK-APPROVER,
        REJREASON TYPE ZEA_AUFK-REJREASON,
        LOEKZ     TYPE ZEA_AUFK-LOEKZ,
        ERNAM     TYPE ZEA_AUFK-ERNAM,
        ERDAT     TYPE ZEA_AUFK-ERDAT,
        ERZET     TYPE ZEA_AUFK-ERZET,
        AENAM     TYPE ZEA_AUFK-AENAM,
        AEDAT     TYPE ZEA_AUFK-AEDAT,
        AEZET     TYPE ZEA_AUFK-AEZET,
      END OF GS_DATA.

DATA GT_DATA LIKE TABLE OF GS_DATA.

DATA: BEGIN OF GS_AUFK.
        INCLUDE STRUCTURE GS_DATA.
DATA:   STATUS          LIKE ICON-ID, " 아이콘
        COLOR           TYPE C LENGTH 4, " 행 색상 정보
        LIGHT           TYPE C,          " 신호등 표시를 위한
        " EXCEPTION 필드
        " 0:비움 1:빨강 2:노랑 3:초록
        IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
        STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
        MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_AUFK.

DATA: GT_AUFK LIKE TABLE OF GS_AUFK.

DATA: BEGIN OF GS_DATA2,
        AUFNR    TYPE ZEA_PPT020-AUFNR,
        ORDIDX   TYPE ZEA_PPT020-ORDIDX,
        MATNR    TYPE ZEA_PPT020-MATNR,
        MAKTX    TYPE ZEA_MMT020-MAKTX,
        BOMID    TYPE ZEA_PPT020-BOMID,
        WERKS    TYPE ZEA_PPT020-WERKS,
        PNAME1   TYPE ZEA_T001W-PNAME1,
        EXPQTY   TYPE ZEA_PPT020-EXPQTY,
        EXPSDATE TYPE ZEA_PPT020-EXPSDATE,
        EXPEDATE TYPE ZEA_PPT020-EXPEDATE,
        SDATE    TYPE ZEA_PPT020-SDATE,
        EDATE    TYPE ZEA_PPT020-EDATE,
        ISPDATE  TYPE ZEA_PPT020-ISPDATE,
        REPQTY   TYPE ZEA_PPT020-REPQTY,
        RQTY     TYPE ZEA_PPT020-RQTY,
        UNIT     TYPE ZEA_PPT020-UNIT,
        LOEKZ    TYPE ZEA_PPT020-LOEKZ,
        ERNAM    TYPE ZEA_PPT020-ERNAM,
        ERDAT    TYPE ZEA_PPT020-ERDAT,
        ERZET    TYPE ZEA_PPT020-ERZET,
        AENAM    TYPE ZEA_PPT020-AENAM,
        AEDAT    TYPE ZEA_PPT020-AEDAT,
        AEZET    TYPE ZEA_PPT020-AEZET,
      END OF GS_DATA2.

DATA: GT_DATA2 LIKE TABLE OF GS_DATA2.

DATA: BEGIN OF GS_PPT020.
        INCLUDE STRUCTURE GS_DATA2.
DATA:   STATUS          LIKE ICON-ID, " 아이콘
        COLOR           TYPE C LENGTH 4, " 행 색상 정보
        LIGHT           TYPE C,          " 신호등 표시를 위한
        " EXCEPTION 필드
        " 0:비움 1:빨강 2:노랑 3:초록
        IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
        STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
        MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_PPT020.

DATA: GT_PPT020 LIKE TABLE OF GS_PPT020.


*-- SCREEN 관련 변수
CONSTANTS: GC_CUSTOM_CONTAINER_NAME TYPE SCRFNAME VALUE 'CCON'.
DATA: OK_CODE TYPE SY-UCOMM.

DATA: BEGIN OF S0110,
        AUFNR      TYPE ZEA_PPT020-AUFNR,
        MATNR      TYPE ZEA_PPT020-MATNR,
        MAKTX      TYPE ZEA_MMT020-MAKTX,
        BOMID      TYPE ZEA_PPT010-BOMID,
        WERKS      TYPE ZEA_PPT020-WERKS,
        PNAME1     TYPE ZEA_T001W-PNAME1,
        PLANID     TYPE ZEA_AUFK-PLANID,
        EXPQTY1    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY2    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY3    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY4    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY5    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY6    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY7    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY8    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY9    TYPE ZEA_PPT020-EXPQTY,
        EXPQTY10   TYPE ZEA_PPT020-EXPQTY,
        EXPQTY11   TYPE ZEA_PPT020-EXPQTY,
        EXPQTY12   TYPE ZEA_PPT020-EXPQTY,
        EXPSDATE1  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE2  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE3  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE4  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE5  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE6  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE7  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE8  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE9  TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE10 TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE11 TYPE ZEA_PPT020-EXPSDATE,
        EXPSDATE12 TYPE ZEA_PPT020-EXPSDATE,
        EXPEDATE1  TYPE ZEA_PPT020-EXPSDATE,
        EXPEDATE2  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE3  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE4  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE5  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE6  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE7  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE8  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE9  TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE10 TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE11 TYPE ZEA_PPT020-EXPEDATE,
        EXPEDATE12 TYPE ZEA_PPT020-EXPEDATE,
        1MONTH     TYPE C,
        2MONTH     TYPE C,
        3MONTH     TYPE C,
        4MONTH     TYPE C,
        5MONTH     TYPE C,
        6MONTH     TYPE C,
        7MONTH     TYPE C,
        8MONTH     TYPE C,
        9MONTH     TYPE C,
        10MONTH    TYPE C,
        11MONTH    TYPE C,
        12MONTH    TYPE C,
        UNIT       TYPE ZEA_PPT020-UNIT,
      END OF S0110.


*-- TREE ALV
DATA: GO_DOCKING_CONTAINER TYPE REF TO CL_GUI_DOCKING_CONTAINER,
      GO_CUSTOM_CONTAINER  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,

      GO_SIMPLE_TREE       TYPE REF TO CL_GUI_SIMPLE_TREE,
      GO_ALV_GRID          TYPE REF TO CL_GUI_ALV_GRID.

*-- 생산오더 HEADER, ITEM ALV
DATA: GO_CONTAINER    TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_SPLIT        TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GO_CON_TOP      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_BOT      TYPE REF TO CL_GUI_CONTAINER,
      GO_ALV_GRID_TOP TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_BOT TYPE REF TO CL_GUI_ALV_GRID.

*-- ALV 관련 변수
DATA: GS_LAYOUT     TYPE LVC_S_LAYO,
      GT_FIELDCAT   TYPE LVC_T_FCAT,
      GS_FIELDCAT   LIKE LINE OF GT_FIELDCAT,
      GT_FIELDCAT2  TYPE LVC_T_FCAT,
      GS_FIELDCAT2  LIKE LINE OF GT_FIELDCAT,
      GT_FIELDCAT3  TYPE LVC_T_FCAT,
      GS_FIELDCAT3  LIKE LINE OF GT_FIELDCAT,
      GT_SORT       TYPE LVC_T_SORT,
      GS_SORT       LIKE LINE OF GT_SORT,
      GS_VARIANT    TYPE DISVARIANT,
      GT_FILTER     TYPE LVC_T_FILT,
      GS_FILTER     TYPE LVC_S_FILT,
      GT_INDEX_ROWS TYPE LVC_T_ROW,
      GS_INDEX_ROW  TYPE LVC_S_ROW,
      GV_SAVE       TYPE C,
      GV_CHECK      TYPE C.

*-- TREE 관련 변수
DATA: BEGIN OF GS_NODE,
        NODE_KEY   TYPE MTREESNODE-NODE_KEY,
        RELATKEY   TYPE MTREESNODE-RELATKEY,
        RELATSHIP  TYPE MTREESNODE-RELATSHIP,
        HIDDEN     TYPE MTREESNODE-HIDDEN,
        DISABLED   TYPE MTREESNODE-DISABLED,
        ISFOLDER   TYPE MTREESNODE-ISFOLDER,
        N_IMAGE    TYPE MTREESNODE-N_IMAGE,
        EXP_IMAGE  TYPE MTREESNODE-EXP_IMAGE,
        STYLE      TYPE MTREESNODE-STYLE,
        LAST_HITEM TYPE MTREESNODE-LAST_HITEM,
        NO_BRANCH  TYPE MTREESNODE-NO_BRANCH,
        EXPANDER   TYPE MTREESNODE-EXPANDER,
        DRAGDROPID TYPE MTREESNODE-DRAGDROPID,
        TEXT       TYPE CHAR60,
      END OF GS_NODE.


DATA: GT_NODE     LIKE TABLE OF GS_NODE,
*      GS_NODE     LIKE LINE OF GT_NODE,
      GV_NODE_KEY TYPE N LENGTH 6.

DATA: BEGIN OF GS_NODE_INFO,
        NODE_KEY LIKE MTREESNODE-NODE_KEY,
        BUKRS    LIKE ZEA_T001W-BUKRS,
        WERKS    LIKE ZEA_T001W-WERKS,
        PNAME1   LIKE ZEA_T001W-PNAME1,
        PDPDAT   LIKE ZEA_PLAF-PDPDAT,
        MATNR    LIKE ZEA_PPT010-MATNR,
        MAKTX    LIKE ZEA_MMT020-MAKTX,
      END OF GS_NODE_INFO,

      GT_NODE_INFO LIKE TABLE OF GS_NODE_INFO.


*----------------------------------------------------------------------*
* Common MACRO
*----------------------------------------------------------------------*
DEFINE _MC_POPUP_CONFIRM.
  CALL FUNCTION 'POPUP_TO_CONFIRM'
    EXPORTING
      TITLEBAR              = &1
*      DISPLAY_CANCEL_BUTTON = ''
      TEXT_QUESTION         = &2
      TEXT_BUTTON_1         = 'YES'
      ICON_BUTTON_1         = '@2K@'
      TEXT_BUTTON_2         = 'NO'
      ICON_BUTTON_2         = '@2O@ '
    IMPORTING
      ANSWER                = &3
    EXCEPTIONS
      TEXT_NOT_FOUND        = 1
      OTHERS                = 2.
END-OF-DEFINITION.
