*&---------------------------------------------------------------------*
*& Include          YE00_EX001_TOP
*&---------------------------------------------------------------------*

" Dictionary Structure
TABLES ZEA_AFRU.

DATA: BEGIN OF GS_AFRU,
        AUFNR     TYPE ZEA_AFRU-AUFNR,
        CHARG     TYPE ZEA_AFRU-CHARG,
        MATNR     TYPE ZEA_AFRU-MATNR,
        MAKTX     TYPE ZEA_MMT020-MAKTX,
        BOMID     TYPE ZEA_AFRU-BOMID,
        EMPCODE   TYPE ZEA_AFRU-EMPCODE,
        TSDAT     TYPE ZEA_AFRU-TSDAT,
        PDQUAN    TYPE ZEA_AFRU-PDQUAN,
        PDBAN     TYPE ZEA_AFRU-PDBAN,
        FNPD      TYPE ZEA_AFRU-FNPD,
        MEINS     TYPE ZEA_AFRU-MEINS,
        DEFREASON TYPE ZEA_AFRU-DEFREASON,
        LOEKZ     TYPE ZEA_AFRU-LOEKZ,
      END OF GS_AFRU,
      GT_AFRU LIKE TABLE OF GS_AFRU.


DATA: BEGIN OF GS_DISPLAY_090.
        INCLUDE STRUCTURE GS_AFRU.

DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_090.

DATA: GT_DISPLAY_090 LIKE TABLE OF GS_DISPLAY_090.


*--
* 두번째 ALV에 출력할 데이터를 보관하는 Internal Table (아래 R)
DATA: BEGIN OF GS_AUFK,
        AUFNR     TYPE ZEA_AUFK-AUFNR,
        WERKS     TYPE ZEA_AUFK-WERKS,
        PLANID    TYPE ZEA_AUFK-PLANID,
        MATNR     TYPE ZEA_AUFK-MATNR,
        MAKTX     TYPE ZEA_MMT020-MAKTX,
        TOT_QTY   TYPE ZEA_AUFK-TOT_QTY,
        MEINS     TYPE ZEA_AUFK-MEINS,
        APPROVAL  TYPE ZEA_AUFK-APPROVAL,
        APPROVER  TYPE ZEA_AUFK-APPROVER,
        REJREASON TYPE ZEA_AUFK-REJREASON,
        LOEKZ     TYPE ZEA_AUFK-LOEKZ,
      END OF GS_AUFK,
      GT_AUFK LIKE TABLE OF GS_AUFK.


DATA: BEGIN OF GS_DISPLAY_070.
        INCLUDE STRUCTURE GS_AUFK.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_070.

DATA: GT_DISPLAY_070 LIKE TABLE OF GS_DISPLAY_070.

*--
* 세번째 ALV에 출력할 데이터를 보관하는 Internal Table (아래 L)
DATA: BEGIN OF GS_PPT020,
        AUFNR    TYPE ZEA_PPT020-AUFNR,
        ORDIDX   TYPE ZEA_PPT020-ORDIDX,
        MATNR    TYPE ZEA_PPT020-MATNR,
        MAKTX    TYPE ZEA_MMT020-MAKTX,
        BOMID    TYPE ZEA_PPT020-BOMID,
        WERKS    TYPE ZEA_PPT020-WERKS,
        EXPQTY   TYPE ZEA_PPT020-EXPQTY,
        EXPSDATE TYPE ZEA_PPT020-EXPSDATE,
        EXPEDATE TYPE ZEA_PPT020-EXPEDATE,
        SDATE    TYPE ZEA_PPT020-SDATE,
        EDATE    TYPE ZEA_PPT020-EDATE,
        ISPDATE  TYPE ZEA_PPT020-ISPDATE,
        REPQTY   TYPE ZEA_PPT020-REPQTY,
        RQTY     TYPE ZEA_PPT020-RQTY,
        UNIT     TYPE ZEA_PPT020-UNIT,
        LOEKZ    TYPE ZEA_PPT020-LOEKZ,
      END OF GS_PPT020,
      GT_PPT020 LIKE TABLE OF GS_PPT020.

DATA: BEGIN OF GS_DISPLAY_120.
        INCLUDE STRUCTURE GS_PPT020.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_120.

DATA: GT_DISPLAY_120 LIKE TABLE OF GS_DISPLAY_120.


DATA: BEGIN OF GS_MMT070,
        MATNR  TYPE ZEA_MMT070-MATNR,
        MAKTX  TYPE ZEA_MMT020-MAKTX,
        WERKS  TYPE ZEA_MMT070-WERKS,
        CHARG  TYPE ZEA_MMT070-CHARG,
        SCODE  TYPE ZEA_MMT070-SCODE,
        CALQTY TYPE ZEA_MMT070-CALQTY,
        REMQTY TYPE ZEA_MMT070-REMQTY,
        MEINS  TYPE ZEA_MMT070-MEINS,
        LVORM  TYPE ZEA_MMT070-LVORM,
      END OF GS_MMT070.

DATA: BEGIN OF GS_DISPLAY_010.
        INCLUDE STRUCTURE GS_MMT070.
DATA:   ICON LIKE ICON-ID, " 아이콘
      END OF GS_DISPLAY_010.

DATA: GT_DISPLAY_010 LIKE TABLE OF GS_DISPLAY_010.


* 화면 관련 변수
DATA: OK_CODE      TYPE SY-UCOMM.

* 화면에 데이터를 출력하기 위한 참조변수
DATA: GO_CONTAINER      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_SPLIT          TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
      GO_CON_TOP_L      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_TOP_R      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_BOT_L      TYPE REF TO CL_GUI_CONTAINER,
      GO_CON_BOT_R      TYPE REF TO CL_GUI_CONTAINER,
      GO_ALV_GRID_TOP_L TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_TOP_R TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_BOT_L TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_BOT_R TYPE REF TO CL_GUI_ALV_GRID.


* ALV 관련 변수
DATA: GS_LAYOUT       TYPE LVC_S_LAYO,
      GT_FIELDCAT_090 TYPE LVC_T_FCAT,
      GS_FIELDCAT_090 TYPE LVC_S_FCAT,
      GT_FIELDCAT_070 TYPE LVC_T_FCAT,
      GS_FIELDCAT_070 TYPE LVC_S_FCAT,
      GT_FIELDCAT_120 TYPE LVC_T_FCAT,
      GS_FIELDCAT_120 TYPE LVC_S_FCAT,
      GT_FIELDCAT_010 TYPE LVC_T_FCAT,
      GS_FIELDCAT_010 TYPE LVC_S_FCAT,
      GS_VARIANT      TYPE DISVARIANT,
      GV_SAVE         TYPE C.
