*&---------------------------------------------------------------------*
*& Include          ZALV_GRID_DISPLAY_TOP
*&---------------------------------------------------------------------*
TABLES: ZEA_PLAF, ZEA_PPT010, ZEA_SDT030, ZEA_STKO, ZEA_STPO, ZEA_MMT010, ZEA_MMT020.

CLASS LCL_EVENT_HANDLER DEFINITION DEFERRED.

CONSTANTS: GC_INSERT         TYPE STRING VALUE 'INSERT',
           GC_DELETE         TYPE STRING VALUE 'DELETE',
           GC_SEMI_RAW_SAPNR TYPE STRING VALUE 'SEMI_RAW_SAPNR',
           GC_SEMI_SAPNR     TYPE STRING VALUE 'SEMI_SAPNR',
           GC_RAW_SAPNR      TYPE STRING VALUE 'RAW_SAPNR',
           GC_MAKE_PLAN      TYPE STRING VALUE 'ADD',
           GC_STATUS         TYPE C VALUE 'X'.

" 생산계획 구조체
DATA: BEGIN OF GS_DATA,
        PLANID    TYPE ZEA_PLAF-PLANID,
        PDPDAT    TYPE n LENGTH 4,
        SAPNR     TYPE ZEA_PLAF-SAPNR,
        WERKS     TYPE ZEA_PPT010-WERKS,
        PNAME1    TYPE ZEA_T001W-PNAME1,
        MATNR     TYPE ZEA_PPT010-MATNR,
        MAKTX     TYPE ZEA_MMT020-MAKTX,
        BOMID     TYPE ZEA_PPT010-BOMID,
        PLANQTY1  TYPE ZEA_PPT010-PLANQTY1,
        PLANQTY2  TYPE ZEA_PPT010-PLANQTY2,
        PLANQTY3  TYPE ZEA_PPT010-PLANQTY3,
        PLANQTY4  TYPE ZEA_PPT010-PLANQTY4,
        PLANQTY5  TYPE ZEA_PPT010-PLANQTY5,
        PLANQTY6  TYPE ZEA_PPT010-PLANQTY6,
        PLANQTY7  TYPE ZEA_PPT010-PLANQTY7,
        PLANQTY8  TYPE ZEA_PPT010-PLANQTY8,
        PLANQTY9  TYPE ZEA_PPT010-PLANQTY9,
        PLANQTY10 TYPE ZEA_PPT010-PLANQTY10,
        PLANQTY11 TYPE ZEA_PPT010-PLANQTY11,
        PLANQTY12 TYPE ZEA_PPT010-PLANQTY12,
        MEINS     TYPE ZEA_PPT010-MEINS,
        STATUS2   TYPE C LENGTH 1,

      END OF GS_DATA.


DATA GT_DATA LIKE TABLE OF GS_DATA.

DATA: BEGIN OF GS_DISPLAY.
        INCLUDE STRUCTURE GS_DATA.
DATA:   STATUS          LIKE ICON-ID, " 아이콘
        COLOR           TYPE C LENGTH 4, " 행 색상 정보
        LIGHT           TYPE C,          " 신호등 표시를 위한
        " EXCEPTION 필드
        " 0:비움 1:빨강 2:노랑 3:초록
        IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
        STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
        MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_DISPLAY.

DATA: GT_DISPLAY LIKE TABLE OF GS_DISPLAY.

" 판매계획 구조체
DATA: BEGIN OF GS_DATA2,
        SAPNR   TYPE ZEA_SDT030-SAPNR,
        WERKS   TYPE ZEA_SDT030-WERKS,
        MATNR   TYPE ZEA_SDT030-MATNR,
        MAKTX   TYPE ZEA_MMT020-MAKTX,
        SAPQU   TYPE ZEA_SDT030-SAPQU,
        SPQTY1  TYPE ZEA_SDT030-SPQTY1,
        SPQTY2  TYPE ZEA_SDT030-SPQTY2,
        SPQTY3  TYPE ZEA_SDT030-SPQTY3,
        SPQTY4  TYPE ZEA_SDT030-SPQTY4,
        SPQTY5  TYPE ZEA_SDT030-SPQTY5,
        SPQTY6  TYPE ZEA_SDT030-SPQTY6,
        SPQTY7  TYPE ZEA_SDT030-SPQTY7,
        SPQTY8  TYPE ZEA_SDT030-SPQTY8,
        SPQTY9  TYPE ZEA_SDT030-SPQTY9,
        SPQTY10 TYPE ZEA_SDT030-SPQTY10,
        SPQTY11 TYPE ZEA_SDT030-SPQTY11,
        SPQTY12 TYPE ZEA_SDT030-SPQTY12,
        MEINS   TYPE ZEA_SDT030-MEINS,
        LOEKZ   TYPE ZEA_SDT030-LOEKZ,
        STATUS2   TYPE ZEA_SDT030-STATUS2,
      END OF GS_DATA2.

DATA: GT_DATA2 LIKE TABLE OF GS_DATA2.


DATA: BEGIN OF GS_DISPLAY2.
      INCLUDE STRUCTURE GS_DATA2.
DATA:
      STATUS          LIKE ICON-ID,    " 아이콘
      COLOR           TYPE C LENGTH 4, " 행 색상 정보
      LIGHT           TYPE C,          " 신호등 표시를 위한
      IT_FIELD_COLORS TYPE LVC_T_SCOL, " 셀 별 색상정보 인터널 테이블
      STYLE           TYPE LVC_T_STYL, " 셀 스타일(모양)
      MARK            TYPE CHAR1,      " 셀의 마킹 정보
      END OF GS_DISPLAY2.

DATA: GT_DISPLAY2 LIKE TABLE OF GS_DISPLAY2.

DATA: BEGIN OF GS_CHECK,
        SAPNR     TYPE ZEA_PLAF-SAPNR,
      END OF GS_CHECK.

      DATA GT_CHECK LIKE TABLE OF GS_CHECK.


DATA: GO_CONTAINER     TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_CONTAINER_2   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV_GRID      TYPE REF TO CL_GUI_ALV_GRID,
      GO_ALV_GRID_2    TYPE REF TO CL_GUI_ALV_GRID,
      GO_EVENT_HANDLER TYPE REF TO LCL_EVENT_HANDLER.

DATA: GS_VARIANT    TYPE DISVARIANT,
      GV_SAVE       TYPE C,

      GT_FIELDCAT   TYPE LVC_T_FCAT,
      GS_FIELDCAT   TYPE LVC_S_FCAT,

      GS_LAYOUT     TYPE LVC_S_LAYO,

      GT_FILTER     TYPE LVC_T_FILT,
      GS_FILTER     TYPE LVC_S_FILT,

      GT_INDEX_ROWS TYPE LVC_T_ROW,
      GS_INDEX_ROWS TYPE LVC_S_ROW,

      GT_TOOLBAR    TYPE UI_FUNCTIONS,

      GT_F4         TYPE LVC_T_F4,
      GS_F4         TYPE LVC_S_F4,

      OK_CODE       TYPE SY-UCOMM,
      GV_LINES      TYPE SY-TFILL,
      GV_ANSWER     TYPE CHAR1,
      GV_CHANGED    TYPE CHAR1,
      GV_SCR_ON     TYPE CHAR1,



      BTN           TYPE CHAR10.

DATA: TOTAL TYPE C LENGTH 14,
      UNIT  TYPE C LENGTH 3.


*----------------------------------------------------------------------*
* Common MACRO
*----------------------------------------------------------------------*
DEFINE _MC_POPUP_CONFIRM.
  CALL FUNCTION 'POPUP_TO_CONFIRM'
    EXPORTING
      TITLEBAR              = &1
*      DISPLAY_CANCEL_BUTTON = ''
      TEXT_QUESTION         = &2
      TEXT_BUTTON_1         = 'YES'
      ICON_BUTTON_1         = '@2K@'
      TEXT_BUTTON_2         = 'NO'
      ICON_BUTTON_2         = '@2O@ '
    IMPORTING
      ANSWER                = &3
    EXCEPTIONS
      TEXT_NOT_FOUND        = 1
      OTHERS                = 2.
END-OF-DEFINITION.
