*&---------------------------------------------------------------------*
*& Include          YE08_EX001_TOP
*&---------------------------------------------------------------------*

TABLES: ZEA_BKPF, ZEA_BSEG, ZEA_SKB1. " G/L계정마스터

* -- G/L 계정에 따른 당기/전기 데이터 합계 조회
* -- ZEA_SKB1-XBILK EQ 'X'. <= 재무제표(대차대조)에 필요한 데이터만 조회
* -- 여기서 필요한 필드 : 계정명 / 금액합계 (금액, 부가세)
* -- ZEA_BSEG, ZEA_SKB1. 두 테이블로 구분 가능함.

DATA: GS_BKPF TYPE ZEA_BKPF,
      GT_BKPF TYPE TABLE OF ZEA_BKPF,

      GS_BSEG TYPE ZEA_BSEG,
      GT_BSEG TYPE TABLE OF ZEA_BSEG,

      GS_SKB1 TYPE ZEA_SKB1,
      GT_SKB1 TYPE TABLE OF ZEA_SKB1.


* -- SELECT * 데이터
DATA: BEGIN OF GS_DATA.
        INCLUDE TYPE ZEA_BSEG.           " 회사코드 / 회계연도 / G/L코드 / GLTXT / 금액/ 세금
DATA:   BUDAT    TYPE ZEA_BKPF-BUDAT,
        XBILK    TYPE ZEA_SKB1-XBILK,    " G/L코드 타입 (NE 'X')
        RECON_YN TYPE ZEA_SKB1-RECON_YN, " 레콘계정 여부
      END OF GS_DATA,
      GT_DATA LIKE TABLE OF GS_DATA.

DATA: GS_DATA1 LIKE GS_DATA,
      GT_DATA1 LIKE TABLE OF GS_DATA, " 1/4 분기
      GS_DATA2 LIKE GS_DATA,
      GT_DATA2 LIKE TABLE OF GS_DATA. " 2/4 분기

* -- 화면에 보여줄 데이터
DATA: BEGIN OF GS_DISPLAY.
DATA:
  COLOR      TYPE C LENGTH 4,
  GLTXT      TYPE ZEA_SKB1-GLTXT, " 계정명
  BPCODE     TYPE ZEA_BSEG-BPCODE, " 계정명
  DMBTR_A    TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-1분기)
  DMBTR_B    TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-2분기)
  DMBTR_C    TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-3분기)
  DMBTR_D    TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-4분기)
  DMBTR_YEAR TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-당기실적)
  DMBTR_PER  TYPE ZEA_BSEG-DMBTR, " 금액합계(2024-합계)
  END OF GS_DISPLAY,
  GT_DISPLAY LIKE TABLE OF GS_DISPLAY.

* -- PDF 변환
DATA:I_T001    TYPE ZEA_FIT000 OCCURS 0,
     PDF       LIKE TLINE OCCURS 0,
     G_SPOOL   TYPE TSP01-RQIDENT,
     G_PROGRAM TYPE SY-REPID VALUE SY-REPID.
TYPE-POOLS:SLIS.
DATA: W_PRINT      TYPE SLIS_PRINT_ALV,
      W_PRINT_CTRL TYPE ALV_S_PCTL.


* -- 100번 화면 변수
*DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
*      GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID.

DATA : GO_CONTAINER        TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GO_ALV_GRID         TYPE REF TO CL_GUI_ALV_GRID,
       GO_BOTTOM_CONTAINER TYPE REF TO CL_GUI_DOCKING_CONTAINER,
       GO_DYNDOC_ID        TYPE REF TO CL_DD_DOCUMENT,
       GO_HTML_CNTRL       TYPE REF TO CL_GUI_HTML_VIEWER.


DATA: OK_CODE TYPE SY-UCOMM.

* -- ALV 관련변수
DATA: GS_LAYOUT   TYPE LVC_S_LAYO,
      GT_FIELDCAT TYPE LVC_T_FCAT,
      GS_FIELDCAT TYPE LVC_S_FCAT,
      GS_SORT     TYPE LVC_S_SORT,
      GT_SORT     TYPE LVC_T_SORT,
      GS_VARIANT  TYPE DISVARIANT,
      GV_SAVE     TYPE C.


* -- 범위값을 가져오는  Range 변수
RANGES: R_SAKNR_4  FOR ZEA_SKB1-SAKNR. " GL계정
RANGES: R_SAKNR_5  FOR ZEA_SKB1-SAKNR. " GL계정
RANGES: R_SAKNR_6  FOR ZEA_SKB1-SAKNR. " GL계정
RANGES: R_SAKNR_7P FOR ZEA_SKB1-SAKNR. " GL계정
RANGES: R_SAKNR_7L FOR ZEA_SKB1-SAKNR. " GL계정


* -- 1분기/ 2분기 날짜를 범위로 받음.
RANGES: R_1 FOR ZEA_BKPF-BUDAT. " 전기일자
RANGES: R_2 FOR ZEA_BKPF-BUDAT. " 전기일자


* --
DATA: BEGIN OF ITAB_DATA OCCURS 0,
        DATANAME(15),
        QUANTITY1    TYPE I,
        QUANTITY2    TYPE I,
        QUANTITY3    TYPE I,
        QUANTITY4    TYPE I,
      END OF ITAB_DATA,
      BEGIN OF ITAB_OPTIONS OCCURS 0,
        OPTION(20),
      END OF ITAB_OPTIONS.
