class ZCL_ZEA_FI090_01_DPC_EXT definition
  public
  inheriting from ZCL_ZEA_FI090_01_DPC
  create public .

public section.
protected section.

  methods BSEGSET_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZEA_FI090_01_DPC_EXT IMPLEMENTATION.


  METHOD BSEGSET_GET_ENTITYSET.

    DATA: GT_FI090 TYPE TABLE OF ZEA_FI090,
          GS_FI090 TYPE ZEA_FI090,
          GT_SKA1  TYPE TABLE OF ZEA_SKA1,
          GS_SKA1  TYPE ZEA_SKA1.

    DATA: GT_DATA_A TYPE TABLE OF ZEA_FI090,
          GT_DATA_B TYPE TABLE OF ZEA_FI090,
          GT_DATA_C TYPE TABLE OF ZEA_FI090,
          GS_DATA_C TYPE ZEA_FI090,
          GS_DATA   TYPE ZEA_FI090,
          GT_DATA_D TYPE TABLE OF ZEA_FI090,
          GT_DATA_E TYPE TABLE OF ZEA_FI090.

    DATA: WRBTR_A TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_B TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_C TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_D TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_E TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_F TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_G TYPE ZEA_BSEG-WRBTR VALUE 0,
          WRBTR_H TYPE ZEA_BSEG-WRBTR VALUE 0.

* --손익계정 ( ALL)
    SELECT
      B~SAKNR   " G/L계정 (Recon)
      C~GLTXT   " G/L계정명
      B~BPCODE
      SUM( B~WRBTR ) AS WRBTR "  통화금액 합계
      B~W_WAERS
*  INTO CORRESPONDING FIELDS OF TABLE ET_ENTITYSET
    INTO CORRESPONDING FIELDS OF TABLE GT_FI090
    FROM ZEA_BKPF AS A        " A: 전표 헤더
   INNER JOIN ZEA_BSEG AS B   " B: 전표 아이템
      ON A~BUKRS EQ B~BUKRS
     AND A~BELNR EQ B~BELNR
     AND A~GJAHR EQ B~GJAHR
   INNER JOIN ZEA_SKB1 AS C   " C: G/L계정마스터
      ON C~BUKRS EQ A~BUKRS
     AND C~SAKNR EQ B~SAKNR
     AND C~GLTXT EQ C~GLTXT
     AND C~XBILK NE 'X'       " G/L코드 Type - 'X': 대차대조 / '' : 손익계산
      GROUP BY B~SAKNR C~GLTXT B~W_WAERS B~BPCODE
      ORDER BY B~BPCODE B~SAKNR ASCENDING.

* -- BP 마스터
    SELECT * FROM ZEA_SKA1 INTO TABLE GT_SKA1.
* --손익계정 ( ALL)
*    SELECT
*      B~SAKNR   " G/L계정 (Recon)
*      C~GLTXT   " G/L계정명
*      SUM( B~WRBTR ) AS WRBTR "  통화금액 합계
*      B~W_WAERS
**  INTO CORRESPONDING FIELDS OF TABLE ET_ENTITYSET
*    INTO CORRESPONDING FIELDS OF TABLE GT_FI090
*    FROM ZEA_BKPF AS A        " A: 전표 헤더
*   INNER JOIN ZEA_BSEG AS B   " B: 전표 아이템
*      ON A~BUKRS EQ B~BUKRS
*     AND A~BELNR EQ B~BELNR
*     AND A~GJAHR EQ B~GJAHR
*   INNER JOIN ZEA_SKB1 AS C   " C: G/L계정마스터
*      ON C~BUKRS EQ A~BUKRS
*     AND C~SAKNR EQ B~SAKNR
*     AND C~GLTXT EQ C~GLTXT
*     AND C~XBILK NE 'X'       " G/L코드 Type - 'X': 대차대조 / '' : 손익계산
*      GROUP BY B~SAKNR C~GLTXT B~W_WAERS
*      ORDER BY B~SAKNR ASCENDING.

* --계정별
    CLEAR: GS_FI090.
    LOOP AT GT_FI090 INTO GS_FI090.


      IF GS_FI090-BPCODE BETWEEN '10000' AND '10009'.
        READ TABLE GT_SKA1 INTO GS_SKA1 WITH KEY BPCODE = GS_FI090-BPCODE.
        GS_FI090-BPCODE = GS_SKA1-BPNAME.
      ELSE.
        GS_FI090-BPCODE = ''.
      ENDIF.

      IF GS_FI090-SAKNR CP '4*'.     " 매출계정
        WRBTR_A = WRBTR_A + GS_FI090-WRBTR.
        COLLECT GS_FI090 INTO GT_DATA_A.

      ELSEIF GS_FI090-SAKNR CP '5*'. " 매출원가 계정
        WRBTR_B = WRBTR_B + GS_FI090-WRBTR.
        COLLECT GS_FI090 INTO GT_DATA_B.

      ELSEIF GS_FI090-SAKNR CP '6*'. " 판관비 계정
        WRBTR_C = WRBTR_C + GS_FI090-WRBTR.

        DATA: LV_FI090 TYPE ZEA_FI090.
        IF GS_FI090-GLTXT EQ '급여'.
          LV_FI090-GLTXT = '급여(영업부장)'.
          LV_FI090-BPCODE = ''.
          LV_FI090-WRBTR = LV_FI090-WRBTR + GS_FI090-WRBTR.
          LV_FI090-W_WAERS = 'KRW'.
        ELSE.
          COLLECT GS_FI090 INTO GT_DATA_C.
        ENDIF.
*        COLLECT GS_FI090 INTO GT_DATA_C.

      ELSEIF GS_FI090-SAKNR BETWEEN '71*' AND '73*'. " 영업외이익 계정
        WRBTR_D = WRBTR_D + GS_FI090-WRBTR.
        COLLECT GS_FI090 INTO GT_DATA_D.

      ELSEIF GS_FI090-SAKNR BETWEEN '74*' AND '79*'. " 영업외비용 계정
        WRBTR_E = WRBTR_E + GS_FI090-WRBTR.
        COLLECT GS_FI090 INTO GT_DATA_E.

      ENDIF.

    ENDLOOP.

    COLLECT LV_FI090 INTO GT_DATA_C.


    CLEAR: GS_FI090.
*    GS_FI090-SAKNR = 'I. 매출액'.
    GS_FI090-GLTXT = 'I. 매출액'.
    GS_FI090-WRBTR = WRBTR_A * 100.
    APPEND GS_FI090 TO ET_ENTITYSET.
    APPEND LINES OF GT_DATA_A TO ET_ENTITYSET.

    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'II. 매출원가'.
    GS_FI090-WRBTR = WRBTR_B * 100.
    APPEND GS_FI090 TO ET_ENTITYSET.
    APPEND LINES OF GT_DATA_B TO ET_ENTITYSET.

    " 매출총이익 = 매출 - 매출원가
    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'III. 매출총이익'.
    GS_FI090-WRBTR = ( WRBTR_A * 100 ) - ( WRBTR_B * 100 ).
    WRBTR_F = ( WRBTR_A * 100 ) - ( WRBTR_B * 100 ).
    APPEND GS_FI090 TO ET_ENTITYSET.

    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'IV. 판매비와관리비'.
    GS_FI090-WRBTR = WRBTR_C * 100.
    APPEND GS_FI090 TO ET_ENTITYSET.
    APPEND LINES OF GT_DATA_C TO ET_ENTITYSET.

    " 영업이익 = 매출총이익 - 판관비
    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'V. 영업이익'.
    GS_FI090-WRBTR = WRBTR_F - ( WRBTR_C * 100 ).
    WRBTR_G = WRBTR_F - ( WRBTR_C * 100 ).
    APPEND GS_FI090 TO ET_ENTITYSET.

    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'VI. 영업외이익'.
    GS_FI090-WRBTR = WRBTR_D * 100.
    APPEND GS_FI090 TO ET_ENTITYSET.
    APPEND LINES OF GT_DATA_D TO ET_ENTITYSET.

    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'VII. 영업외비용'.
    GS_FI090-WRBTR = WRBTR_E * 100.
    APPEND GS_FI090 TO ET_ENTITYSET.
    APPEND LINES OF GT_DATA_E TO ET_ENTITYSET.

    " 당기순이익 = 영업이익 + 영업외이익 - 영업외비용
    CLEAR: GS_FI090.
    GS_FI090-GLTXT = 'VIII. 당기순이익'.
    GS_FI090-WRBTR = WRBTR_G + ( WRBTR_D * 100 ) - ( WRBTR_E * 100 ).
    APPEND GS_FI090 TO ET_ENTITYSET.

  ENDMETHOD.
ENDCLASS.
