class ZCL_ZEA_FI050_01_DPC_EXT definition
  public
  inheriting from ZCL_ZEA_FI050_01_DPC
  create public .

public section.
protected section.

  methods TCURRSET_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZEA_FI050_01_DPC_EXT IMPLEMENTATION.


  METHOD TCURRSET_GET_ENTITYSET.

    DATA: GT_TCURR TYPE TABLE OF ZEA_FI050,
          GS_TCURR TYPE ZEA_FI050,
          LV_TOTAL TYPE P LENGTH 9 DECIMALS 5.
    DATA: LS_FILT TYPE /IWBEP/S_MGW_SELECT_OPTION,
          LT_FILT TYPE TABLE OF /IWBEP/S_MGW_SELECT_OPTION.
    DATA: LV_GDATU TYPE STRING,
          LT_SO    TYPE TABLE OF /IWBEP/S_COD_SELECT_OPTION,
          LS_SO    LIKE LINE OF LT_SO.
    DATA: LV_LOW  TYPE STRING,
          LV_HIGH TYPE STRING.
    DATA: LV_DIFFER TYPE ZEA_FI050-DIFFER.
*

    IF IT_FILTER_SELECT_OPTIONS IS NOT INITIAL.
      LT_FILT = IT_FILTER_SELECT_OPTIONS.

      READ TABLE LT_FILT INTO LS_FILT INDEX 1.
      LV_GDATU = LS_FILT-PROPERTY.
      LT_SO    = LS_FILT-SELECT_OPTIONS.

      READ TABLE LT_SO INTO LS_SO INDEX 1.
      LV_LOW  = LS_SO-LOW.
      LV_HIGH = LS_SO-HIGH.

      IF SY-SUBCS EQ 0.
        SELECT * FROM ZEA_TCURR
          INTO CORRESPONDING FIELDS OF TABLE GT_TCURR
        WHERE TCURR EQ 'USD'
          AND GDATU BETWEEN LV_LOW AND LV_HIGH
          ORDER BY GDATU.
      ENDIF.
    ELSE.

      SELECT * FROM ZEA_TCURR
        INTO CORRESPONDING FIELDS OF TABLE GT_TCURR
        WHERE TCURR EQ 'USD'
        ORDER BY GDATU.
    ENDIF.

    " 값 보정
    LOOP AT GT_TCURR INTO GS_TCURR.
      IF GS_TCURR-TCURR EQ 'IDR(1'.
        GS_TCURR-TCURR = 'IDR'.
      ELSEIF GS_TCURR-TCURR EQ 'JPY(1'.
        GS_TCURR-TCURR = 'JPY'.
      ENDIF.
      MODIFY GT_TCURR FROM GS_TCURR TRANSPORTING TCURR.
    ENDLOOP.

    " 평균환율
    LOOP AT GT_TCURR INTO GS_TCURR.
      LV_TOTAL = LV_TOTAL + GS_TCURR-UKURS.

      GS_TCURR-AVERAGE = LV_TOTAL / SY-TABIX. " <== 환율 평균

      " 환율과 평균환율의 차이
      LV_DIFFER = GS_TCURR-UKURS - GS_TCURR-AVERAGE.

      " 환율과 평균환율의 차이를 백분율로 계산
      IF GS_TCURR-AVERAGE <> 0.
        GS_TCURR-DIFFER = ( LV_DIFFER / GS_TCURR-AVERAGE ) * 100.
      ELSE.
        " 평균환율이 0이면 백분율은 0으로 설정
        GS_TCURR-DIFFER = 0.
      ENDIF.
      MODIFY GT_TCURR FROM GS_TCURR TRANSPORTING AVERAGE DIFFER.

    ENDLOOP.

*
    APPEND LINES OF GT_TCURR TO ET_ENTITYSET.




  ENDMETHOD.
ENDCLASS.
