FUNCTION-POOL ZEA_FI_WL.                    "MESSAGE-ID ..

* INCLUDE LZEA_FI_KAD...                     " Local class definition

  TABLES: ZEA_BKPF, ZEA_BSEG. " FI 헤더/아이템
  TABLES: ZEA_SKB1.  " G/L마스터

  " FI 전표 헤더 테이블
  DATA: GT_BKPF TYPE TABLE OF ZEA_BKPF,
        GS_BKPF TYPE ZEA_BKPF.

  " FI 전표 아이템 테이블
  DATA: GT_BSEG TYPE TABLE OF ZEA_BSEG,
        GS_BSEG TYPE ZEA_BSEG.

  " FI G/L계정
  DATA: GT_SKB1 TYPE TABLE OF ZEA_SKB1,
        GS_SKB1 TYPE ZEA_SKB1.

  DATA : GV_RECON TYPE ZEA_SKB1-SAKNR. " G/L코드를 찾기 위한 변수

  " MM 헤더 테이블
  DATA: GS_MMT090 TYPE ZEA_MMT090,
        GT_MMT090 TYPE TABLE OF ZEA_MMT090.

  " MM 아이템 테이블
  DATA: GS_MMT100 TYPE ZEA_MMT100,
        GT_MMT100 TYPE TABLE OF ZEA_MMT100.

  " BAPI - 금액변환 함수
  DATA : LV_CURR       LIKE TCURC-WAERS,
         LV_BEFORE_AMT LIKE BAPICURR-BAPICURR,
         LV_AFTER_AMT  LIKE BAPICURR-BAPICURR.
  DATA: GV_TOTAL       LIKE GS_BSEG-DMBTR VALUE 0.

* --FI 전표번호 채번
  DATA: GV_BELNR_NUMBER TYPE ZEA_BKPF-BELNR.      " 전표번호(key)
  DATA: GV_ITNUM TYPE N.                          " Item 라인번호

  DATA:
    IV_MBLNR   TYPE  ZEA_MMT090-MBLNR,
    IV_BUDAT   TYPE  ZEA_MMT090-BUDAT,
    IV_MATNR   TYPE  ZEA_MMT100-MATNR,
    IV_BWART   TYPE  ZEA_MMT100-BWART,
    IV_PLANTFR TYPE  ZEA_MMT100-PLANTFR,
    IV_PLANTTO TYPE  ZEA_MMT100-PLANTTO,
    IV_DMBTR   TYPE  ZEA_MMT100-DMBTR,
    IV_MENGE   TYPE  ZEA_MMT100-MENGE,
    IV_WAERS1  TYPE  ZEA_MMT100-WAERS1,
    IV_VENCODE TYPE  ZEA_MMT100-VENCODE,
    IV_CUSCODE TYPE  ZEA_MMT100-CUSCODE.
